version: '3'

# See https://taskfile.dev/usage/

tasks:
  default:
    cmds:
      - task: generate-packages

  generate-packages:
    desc: Runs Helm for all chart dirs and commits results in artefact branch
    vars:
      BRANCH:
        sh: git name-rev --name-only HEAD
      CHARTS:
        sh: find . -mindepth 2 -maxdepth 2  -type f -name "Chart.yaml" -exec dirname "{}" \; | xargs basename
    cmds:
      - for: CHARTS
        cmd: helm package -d charts {{ .ITEM }}
      - git stash
      - git checkout gh-pages
      - git stash pop
      - for: CHARTS
        cmd: git add charts/{{.ITEM}}
      - git push
      - git checkout {{ .BRANCH }}

