{{- if .Values.mount.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
  namespace: {{ include "tnssca.fullname" . }}
type: Opaque
data:
{{ ($.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end }}
