{{- if .Values.mount.secrets }}
{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
  namespace: {{ include "tnssca.fullname" . }}
type: Opaque
data:
{{- range $k,$v := .Values.secrets }}
{{ $k | indent 2 }}: {{ $v | b64enc }}
{{- end }}
{{- end }}