version: '3'

#
# Sample Taskfile for generating a deployment descriptor for quay.io/basen/lm-trainn, 
# providing a node directory mount, a password file as a secret, and a number of 
# required deployment ENV vars. 
#
# To generate a deployment 'myuniqueid':
#
# LEEMAIL=your@letsencrypt.email \
# INSTANCE=myuniqueid \
# HOSTPATH=/data/services/myuniqueid \
# task -t Taskfile-trle1.yml
#
#
# See also: https://taskfile.dev/usage/
#


env:
  OCI_EXE: '{{.OCI_EXE | default "podman"}}'
vars:
  CHART: ruori/traefik-rproxy-le-1
  CHARTLOCAL: ./charts/traefik-rproxy-le-1

tasks:
  default:
    cmds:
      - task: generate-deployment

  clean:
    cmds:
      - rm -rf ./secrets

  helm-gen-template:
    internal: true
    dir: '{{.USER_WORKING_DIR}}'
    desc: Runs helm to generate a Traefik LE 1-node rproxy.
    vars: 
      OUT:
        sh: echo "{{.USER_WORKING_DIR}}/deploy-${INSTANCE}-$(date +%Y%m%dT%H%M%S%z).yaml"
    requires:
      vars: [INSTANCE,LEEMAIL,HOSTPATH]
    cmds:
      - echo "Generating $OUT..."
      - >
        helm template \
          --set traefik.persistence.hostpath="{{.HOSTPATH}}" \
          --set traefik.instanceLabelOverride="{{.INSTANCE}}" \
          --set traefik.namespaceOverride="{{.INSTANCE}}" \
          --set traefik.certificatesResolvers.letsencrypt.acme.email="{{.LEEMAIL}}" \
          {{.INSTANCE}} {{.TCHART}} >{{.OUT}}
      - |
        {{if eq OS "linux"}}sed{{else if eq OS "darwin"}}gsed{{end}} -i 's/--api.dashboard=true/--api.dashboard=false/g' {{.OUT}}
      - |
        {{if eq OS "linux"}}sed{{else if eq OS "darwin"}}gsed{{end}} -i 's/--metrics.prometheus=true/--metrics.prometheus=false/g' {{.OUT}}
      - >
        echo -e "Done. Remember to perform the following tasks:\n
        - apply the CRDs on your cluster\n
        - deploy {{.OUT}} on your cluster\n
        - create $HOSTPATH on cluster host(s)\n
        - configure your DNS to point to your added hostname\n"

  generate-deployment:
    desc: Generate a deployment descriptor for Traefik LE 1-node rproxy.
    cmds:
      - task: helm-gen-template
        vars: { TCHART: '{{.CHART}}' }

  test-local:
    desc: Use local files to test the Traefik LE 1-node rproxy chart.
    cmds:
      - task: helm-gen-template
        vars: { TCHART: '{{.CHARTLOCAL}}' }
