{{/* Policy to allow traefik network ingress into namespaced deployment.
     Any .Values.traefik.ports entry with pass=true is included. */}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external
  namespace: {{ template "subtraefik.namespace" . }}
spec:
  ingress:
  - from: []
    ports:
{{- range $name, $config := .Values.traefik.ports }}
    - port: {{ default $config.port $config.containerPort }}
      protocol: {{ $config.protocol }}
{{- end }}
  podSelector:
    matchLabels:
      networking/allow-internet-ingress: "true"
