apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.traefik.persistence.name }}
  namespace: {{ template "subtraefik.namespace" . }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.traefik.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.traefik.persistence.hostpath }}"