{{- range $module, $config := .Values.modules.core }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $module }}
  namespace: {{ $.Values.deployment.namespace }}{{/* see https://stackoverflow.com/questions/55213545/helm-range-without-leaving-global-scope */}}
  labels:
    instance: instance-{{ $.Values.deployment.name }}
    name: {{ $module }}
    module: {{ $module }}
spec:
  selector:
    matchLabels:
      instance: instance-{{ $.Values.deployment.name }}
      name: {{ $module }}
      module: {{ $module }}
  replicas: 1
  template:
    metadata:
      labels:
        instance: instance-{{ $.Values.deployment.name }}
        name: {{ $module }}
        module: {{ $module }}
    spec:
      # imagePullSecrets: 
      # - name: local-registry
#      initContainers:
#      - name: init-{{ $module }}
#        image: busybox:1.33.1
#        command: ['sh', '-c', 'cp /etc/{{ $module }}/.secrets/userdb.bolt /etc/{{ $module }}/userdb.bolt']
      volumes:
        {{- if $config.secrets }}
        - name: volsecrets
          secret:
            secretName: {{ $module }}-deploy-secrets
        {{- end }}
      containers:
      - name: {{ $module }}
        image: {{ $config.image }}
        imagePullPolicy: {{ or $config.imagePullPolicy "Always" }}
        ports:
        - containerPort: {{ required "missing containerPort" $config.ports.containerPort }}
        env:
        {{- range $kv := $config.env }}
        - name: {{$kv.name}}
          value: "{{$kv.value}}"
        {{- end }}
        volumeMounts:
        {{- if $config.secrets }}
          - name: volsecrets
            mountPath: {{ $config.secrets.mount }}
            readOnly: {{ $config.secrets.readOnly }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          {{- if and $config.securityContext $config.securityContext.uidgid }}
          runAsUser: {{ splitList ":" $config.securityContext.uidgid | first }}
          runAsGroup: {{ splitList ":" $config.securityContext.uidgid | last }}
          {{- end }}
#        nodeSelector: 
#          accel: nvidia
{{- end }}
