---
{{- range $module, $config := .Values.modules }}
{{- if $config.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: sikrits-{{ $module }}
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
{{- range $k,$v := $config.secrets.files }}
  {{ $k }}: |
{{ $v | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
