{{- range $module, $config := .Values.modules.user }}
{{- if $config.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $module }}-deploy-secrets
  namespace: {{ $.Values.deployment.namespace }}
type: Opaque
data:
{{- range $k,$v := $config.secrets.files }}
  {{ $k }}: |
{{ $v | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
