{{- range $module, $config := .Values.modules.user }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $module }}
  labels:
    instance: instance-{{ $.Values.deployment.name }}
    name: {{ $module }}
    module: {{ $module }}
spec:
  ports:{{/* for now only a single port actually supported! */}}
  - protocol: TCP
    port: {{ or $config.ports.containerPort 9191 }}
    targetPort: {{ or $config.ports.containerPort 9191 }}
  selector:
    module: {{ $module }}
    instance: {{ $.Values.deployment.name }}
{{- end }}
