{{- range $module, $config := .Values.modules.core }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $module }}
  namespace: {{ $.Values.deployment.namespace }}
  labels:
    instance: instance-{{ $.Values.deployment.name }}
    name: {{ $module }}
    module: {{ $module }}
spec:
#  clusterIP: None # for headless!
  ports:
  - protocol: TCP
    port: {{ required "missing containerPort" $config.ports.containerPort }}{{/* port setup still WIP */}}
    targetPort: {{ required "missing containerPort" $config.ports.containerPort }}
  selector:
    module: {{ $module }}
    instance: instance-{{ $.Values.deployment.name }}
{{- end }}
