{{- range $module, $config := .Values.modules.core }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $module }}
  namespace: {{ $.Values.deployment.namespace }}
  labels:
    instance: instance-{{ $.Values.deployment.name }}
    name: {{ $module }}
    module: {{ $module }}
spec:
  #  clusterIP: None # for headless!
  ports:
  {{- range $config.entryPoints }}
    - protocol: TCP
      port: {{ required "missing containerPort" .containerPort }}
      targetPort: {{ required "missing containerPort" .containerPort }}
  {{- end }}
  selector:
    module: {{ $module }}
    instance: instance-{{ $.Values.deployment.name }}
{{- end }}